In [1]:
pip install cmake

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.


In [3]:
# pip uninstall numpy

In [4]:
# pip install numpy==1.24.4

In [5]:
# pip install dlib (manual installation required)

In [6]:
pip install "C:\Users\azefr\OneDrive\Desktop\Face Recoginition\dlib-19.22.99-cp38-cp38-win_amd64.whl"

Processing c:\users\azefr\onedrive\desktop\face recoginition\dlib-19.22.99-cp38-cp38-win_amd64.whl
dlib is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
Note: you may need to restart the kernel to use updated packages.


In [7]:
pip install face_recognition

Note: you may need to restart the kernel to use updated packages.


In [8]:
import os
import cv2
import numpy as np
import face_recognition as fr

In [9]:
path = 'images'

In [10]:
mylist = os.listdir(path)
mylist

['hrithik roshan.jpg',
 'ranveer kapoor.jpg',
 'ranveer.jpg',
 'shahid kapoor.jpeg',
 'sharukh khan.webp']

In [11]:
imgs = []
classnames = []

In [12]:
for img in mylist:
    imgpath = os.path.join(path,img)
    # print(imgpath)
    current_img = cv2.imread(imgpath)
    # print(current_img)
    imgs.append(current_img)
    classnames.append(img.split('.')[0])
print(classnames)

['hrithik roshan', 'ranveer kapoor', 'ranveer', 'shahid kapoor', 'sharukh khan']


In [14]:
img = imgs[0]

# if img is None:
#     raise ValueError("Image not loaded properly! Check the file path or source.")

img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

# img = img.copy()
# img = np.array(img, dtype=np.uint8)
print("Image dtype:", img.dtype)  # Should be 'uint8'
print("Image shape:", img.shape) 
# # Display the image
# plt.imshow(img)
# plt.axis("off")
# plt.show()

face_in_frame = fr.face_locations(img)
# print(face_in_frame)
# img = np.array(img, dtype=np.uint8)
print(face_in_frame)
encode = fr.face_encodings(img,face_in_frame)[0]
print(encode)


Image dtype: uint8
Image shape: (224, 225, 3)
[(66, 156, 129, 93)]
[-0.15265851  0.00722919  0.11261612 -0.07127737 -0.12887534 -0.02122906
  0.03184689 -0.03055483  0.1287151  -0.07650042  0.16983692 -0.07578363
 -0.30878589  0.083482   -0.06014826  0.0501892  -0.0876535  -0.12648024
 -0.1153122  -0.02093035  0.05720904  0.06788141 -0.00590056  0.0238278
 -0.13928068 -0.30676913 -0.09179072 -0.10091671  0.02505412 -0.11688953
 -0.05445293 -0.0077648  -0.19861041 -0.09335507 -0.01308127  0.10527957
  0.00197729 -0.06833384  0.22237486  0.03899086 -0.12928735  0.03557597
  0.05671737  0.29160389  0.02974807  0.12328318 -0.00654254  0.04624553
  0.12201606 -0.31743789  0.14002065  0.06570737  0.18909171  0.00556081
  0.16799465 -0.24619904  0.02723115  0.15465502 -0.20422547  0.24244875
  0.04345032 -0.04560971 -0.00603477 -0.07363306  0.22181043  0.10567259
 -0.06655937 -0.09279846  0.19141525 -0.10918514 -0.02543028  0.0274453
 -0.08582523 -0.11207507 -0.18609989  0.0743442   0.3513312

In [15]:
def faceencodings(images):
    encoding_list = []
    for i in imgs:
        img = cv2.cvtColor(i,cv2.COLOR_BGR2RGB)
        face_in_frame = fr.face_locations(img)
        if face_in_frame:
            encode = fr.face_encodings(img, face_in_frame)[0]  # Fix: Pass `img` as the first argument
            encoding_list.append(encode)
        else:
            print("⚠️ No face detected in an image, skipping encoding.")

    return encoding_list

In [ ]:
encodelist_knownfaces=faceencodings(imgs)
encodelist_knownfaces

[array([-0.15265851,  0.00722919,  0.11261612, -0.07127737, -0.12887534,
        -0.02122906,  0.03184689, -0.03055483,  0.1287151 , -0.07650042,
         0.16983692, -0.07578363, -0.30878589,  0.083482  , -0.06014826,
         0.0501892 , -0.0876535 , -0.12648024, -0.1153122 , -0.02093035,
         0.05720904,  0.06788141, -0.00590056,  0.0238278 , -0.13928068,
        -0.30676913, -0.09179072, -0.10091671,  0.02505412, -0.11688953,
        -0.05445293, -0.0077648 , -0.19861041, -0.09335507, -0.01308127,
         0.10527957,  0.00197729, -0.06833384,  0.22237486,  0.03899086,
        -0.12928735,  0.03557597,  0.05671737,  0.29160389,  0.02974807,
         0.12328318, -0.00654254,  0.04624553,  0.12201606, -0.31743789,
         0.14002065,  0.06570737,  0.18909171,  0.00556081,  0.16799465,
        -0.24619904,  0.02723115,  0.15465502, -0.20422547,  0.24244875,
         0.04345032, -0.04560971, -0.00603477, -0.07363306,  0.22181043,
         0.10567259, -0.06655937, -0.09279846,  0.1

: 

In [ ]:
video = cv2.VideoCapture(0)
while True:
    syc,frame = video.read()
    frame1 = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
    face_in_frame = fr.face_locations(frame1)
    # print(face_in_frame)
    encoded_face = fr.face_encodings(frame1,face_in_frame)
    # print(encoded_face)
    for enc_face,faceloc in zip(encoded_face,face_in_frame):
        matches = fr.compare_faces(encodelist_knownfaces,enc_face)
        print(matches)

        face_dis = fr.face_distance(encodelist_knownfaces,enc_face)
        print(face_dis)

        match_indx = np.argmin(face_dis)
        if matches[match_indx]:
            name = classnames[match_indx]
            # print(match_indx)
        else:
            name = "Unknown" 
        
        y1,x2,y2,x1 = faceloc
        cv2.rectangle(frame,(x1,y1),(x2,y2),(0,0,255),2)
        cv2.putText(frame,name,(x1,y1),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,0),2)

    cv2.imshow("face",frame)
    if cv2.waitKey(1)&0XFF==ord('q'):
        break
video.release()
cv2.destroyAllWindows()

[False, False, False, False, False]
[0.79453872 0.70233024 0.78602088 0.6730778  0.69271847]
[False, False, False, False, False]
[0.80418829 0.69949362 0.78673765 0.68558932 0.68551904]
[False, False, False, False, False]
[0.79139775 0.69855097 0.79032429 0.68238704 0.69248889]
[False, False, False, False, False]
[0.80081237 0.70759704 0.79433359 0.67691785 0.69712461]
[False, False, False, False, False]
[0.79670263 0.68362842 0.77769121 0.67790775 0.68431055]
[False, False, False, False, False]
[0.78628201 0.68964009 0.77824408 0.67206044 0.68808586]
[False, False, False, False, False]
[0.79375021 0.69451479 0.77918207 0.67961549 0.69959036]
[False, False, False, False, False]
[0.78725196 0.69052115 0.78763126 0.67982784 0.69196061]
[False, False, False, False, False]
[0.78527603 0.69065217 0.78157049 0.67804562 0.67376002]
[False, False, False, False, False]
[0.77312378 0.679276   0.76918683 0.68485581 0.67314792]
[False, False, False, False, False]
[0.79694799 0.69904786 0.78715481 